
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/udemymicroservice
    username: postgres
    password: hari
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect




